### ISSUE TITLE
Just a few suggestions😊

### ISSUE THREAD

**Issue by Flyrder** [gracefullight/dekakao#1]
kakaoT can be replaced by SWING

Not recommend NaverMap as kakaoMap alternative.
(They're both the same. ㅋㅋ)

switch phone number region to the service not available could keep a ton of privacy?
like china mainland or canada..

Anyway, thanks for your project😄

**Comment by gracefullight** [comment]
In the case of Naver, I couldn't find any back data related to censorship, but there are no other alternatives. I also took the opportunity to improve the old code. 

Thank you for your interest in this repository.
